global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 10s

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 20s
    metrics_path: /metrics

  - job_name: "custom-exporter"
    static_configs:
      - targets: ["custom-exporter:8000"]
    scrape_interval: 20s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
